name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        install_components: kubectl

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy-Dev
      env:
        CLOUDSDK_PYTHON: /usr/bin/python3
      run: |
        gcloud components update
        gcloud container clusters get-credentials reference-baton-426923-t0-gke --region us-east5 --project reference-baton-426923-t0
        helm repo add harbor https://helm.goharbor.io
        helm install my-harbor harbor/harbor --version 1.15.0
        ls
        kubectl install my-harbor bitmani/harbor -f values.yaml -f dev-values.yaml -n harbor

    - name: Deploy-Prod
      env:
        CLOUDSDK_PYTHON: /usr/bin/python3
      run: |
        gcloud components update
        gcloud container clusters get-credentials reference-baton-426923-t0-gke-prod --region us-east5 --project reference-baton-426923-t0
        helm repo add harbor https://helm.goharbor.io
        helm install my-harbor harbor/harbor --version 1.15.0
        ls
        kubectl install my-harbor bitmani/harbor -f values.yaml -f prod-values.yaml -n harbor
